services:
  sftp-server:
    build:
      context: .
      args:
        BACKUP_PASSWORD: ${BACKUP_PASSWORD:-changeme}
    container_name: sftp-server
    hostname: sftp-server
    volumes:
      - ./uploads:/home/backup/chroot/uploads # Uploads directory (persisted on host)
    ports:
      - 2222:2222
    restart: unless-stopped
